name: Build Succeeds on PR
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Dependencies
        run: |
          echo "NODE_PATH=$NODE_PATH:$GITHUB_WORKSPACE" >> $GITHUB_ENV
          npm ci
        working-directory: paytm_turbo
      - name: Generate Prisma Client
        run: npm run db:generate
        working-directory: paytm_turbo  
      - name: Debug @repo/ui Dist Before Build
        run: ls -la packages/ui/dist || echo "Dist folder not found yet"
        working-directory: paytm_turbo
      - name: Build @repo/ui Explicitly
        run: npm run build
        working-directory: paytm_turbo/packages/ui
      - name: Debug @repo/ui Dist After @repo/ui Build
        run: ls -la packages/ui/dist || echo "Dist folder still not found after @repo/ui build"
        working-directory: paytm_turbo
      - name: Run Full Turbo Build
        run: npm run build
        working-directory: paytm_turbo
      - name: Debug @repo/ui Dist After Full Build
        run: ls -la packages/ui/dist
        working-directory: paytm_turbo